name: table_reserver
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  carousel_slider: 4.2.1
  collection: 1.19.1
  cupertino_icons: 1.0.8
  date_picker_plus: 4.1.0
  dio: 5.7.0
  fl_chart: 0.68.0
  flutterflow_ui: 0.3.1
  flutter_advanced_table: 1.1.5
  flutter_animate: 4.5.0
  flutter_launcher_icons: 0.13.1
  flutter_rating_bar: 4.0.1
  flutter_spinkit: 5.2.0
  flutter_staggered_grid_view: 0.7.0
  font_awesome_flutter: 10.8.0
  from_css_color: 2.0.0
  dropdown_button2: 2.3.9
  geocoding: 2.0.4
  geolocator: 8.2.0
  go_router: 12.1.3
  google_maps_flutter: 2.6.1
  google_sign_in: 7.1.1
  http: 1.2.1
  html: 0.15.6
  loading_animation_widget: 1.3.0
  logger: 2.5.0
  percent_indicator: 4.2.2
  provider: 6.1.2
  rating_summary: 1.0.4
  shared_preferences: 2.5.3
  smooth_page_indicator: 1.2.1
  toastification: 2.3.0
  url_launcher: 6.2.5

dependency_overrides:
  carousel_slider:
    path: lib/_patched_packages/carousel_slider
  flutterflow_ui:
    path: lib/_patched_packages/flutterflow_ui

flutter_launcher_icons:
  ios: true
  image_path: "lib/assets/icons/appIcon.png"

dev_dependencies:
  flutter_lints: 6.0.0
  test: 1.26.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/appIcon.png
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
          weight: 700
