name: TableReserver
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  carousel_slider: 4.2.1
  collection: 1.17.2
  cupertino_icons: 1.0.8
  date_picker_plus: 4.1.0
  dio: 5.7.0
  dropdown_button2: 2.3.9
  flutterflow_ui: 0.2.0+1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_credit_card: 3.0.6
  flutter_launcher_icons: 0.13.1
  flutter_osm_plugin: 0.70.0
  flutter_rating_bar: 4.0.1
  flutter_spinkit: 5.2.0
  flutter_staggered_grid_view: 0.6.2
  flutter_styled_toast: 2.2.1
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_maps_flutter: 2.5.3
  google_fonts: 4.0.3
  geolocator: 8.2.0
  geocoding: 2.0.4
  http: 0.13.3
  logger: 2.5.0
  provider: 6.0.4
  rating_summary: 1.0.4
  url_launcher: 6.2.2

flutter_launcher_icons:
  ios: true
  image_path: "lib/assets/icons/appIcon.png"

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/appIcon.png
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
          weight: 700
